import type { Offer } from "./types";

/**
 * The directory. Agent products come first: an agent can verify an offer and pay
 * for it in one HTTP round trip, with no procurement. Services come next: they
 * bring the larger tickets and teach us what to productize.
 */
export const offers: readonly Offer[] = [
  // ─── For agents: paid per call, no account, no API key ──────────────────────
  {
    slug: "shonin-check",
    name: "Shonin Check",
    category: "agent-api",
    status: "beta",
    featured: true,
    oneLiner: "Should my agent pay this? A pre-payment check of any x402 payment request: pay, confirm with a person, or block.",
    pitch:
      "A pre-payment check for AI agents that pay: send the 402 payment request before signing, and get back pay, confirm or block with the reasons: a known stablecoin, the amount against your budget, a real payee, the right signing domain, the host you called, and whether the purchase serves the user's task",
    audience: ["agents", "builders", "startup"],
    unit: "One check of one payment request",
    intake: [
      "The PAYMENT-REQUIRED header, or its decoded JSON",
      "The URL the agent called",
      "Optional: the user's task, a budget and a payee allowlist",
    ],
    engine:
      "Code checks every payment option against the x402 SDK's own token tables. Only when those pass, and a task is given, does the brain answer whether the purchase serves it. The model can lower a verdict, never raise it.",
    rulebook: [
      "Code checks run first; a failed code check blocks without asking a model.",
      "Unknown tokens, testnets and mismatched signing domains always go to a person.",
      "Anything above the caller's auto-approve limit (default $0.10) goes to a person, whatever the model says.",
      "A model can block a payment. It can never raise a limit.",
    ],
    review: "Automated: every verdict lists the checks it ran and their results.",
    delivery: "JSON: the verdict, the reasons, the chosen payment option and every check.",
    turnaround: "Under a second without a task; a few seconds with the intent check",
    price: {
      label: "$0.01 per check",
      humanAlternative: "A person approving every agent payment by hand, or no check at all",
      model: "per-call",
    },
    distribution: ["x402 Bazaar, llms.txt and the agent card", "MCP registries", "Agent wallet and framework builders", "x402 and MPP hackathons"],
    split: {
      llm: "Nothing: the verdict is structured",
      decide: "Does the purchase serve the task; does the offer look real",
      code: "Token, amount, budget, payee, signing-domain and host checks; the auto-approve limit",
    },
    tags: ["x402", "agents", "payments", "security", "trust"],
    api: {
      method: "POST",
      path: "/api/v1/check",
      priceUsd: 0.01,
      description: "Should my agent pay this? Send an x402 PAYMENT-REQUIRED and get pay, confirm or block, with the reasons.",
      inputExample: {
        paymentRequired: "<the PAYMENT-REQUIRED header value>",
        url: "https://api.example.com/v1/rates",
        task: "Get today's USD/EUR rate for the invoice",
        budgetUsd: 0.05,
      },
    },
  },
  {
    slug: "shonin-gate",
    name: "Shonin Gate",
    category: "agent-api",
    status: "beta",
    featured: true,
    oneLiner: "Execute, confirm or escalate? An approval gate for any agent action, with one confidence bar per risk tier.",
    pitch:
      "An approval gate for AI agents: before an agent sends, deletes, books or pays, it asks whether to execute now, ask a person to confirm, or hand it to a person, judged against the user's request with calibrated confidence and a stricter bar for riskier actions",
    audience: ["agents", "builders", "startup", "enterprise"],
    unit: "One gate decision for one proposed action",
    intake: [
      "The action the agent is about to take",
      "What the user asked for",
      "The risk tier: read, write, external, money or irreversible",
      "Optional: context from the conversation",
    ],
    engine:
      "The brain answers three typed questions: does the action match the request, did the user approve it, is it riskier than stated. The policy gate decides by tier. Money and irreversible actions are prepared, never executed.",
    rulebook: [
      "One bar per risk tier: read .5, write .7, external .85, money .9, irreversible .95.",
      "Money and irreversible actions are at most prepared for a person to confirm.",
      "An action that looks riskier than stated gets the external bar.",
      "Callers can raise the bar, never lower it.",
    ],
    review: "Automated: every verdict carries its confidence, threshold and reason.",
    delivery: "JSON: the verdict, the reason, confidence, threshold, the tier applied and the decision log.",
    turnaround: "A few seconds",
    price: {
      label: "$0.01 per gate",
      humanAlternative: "A person reviewing every agent action, or an agent acting unchecked",
      model: "per-call",
    },
    distribution: ["x402 Bazaar, llms.txt and the agent card", "MCP registries", "Agent framework communities", "Teams deploying agents into regulated work"],
    split: {
      llm: "Nothing: the verdict is structured",
      decide: "Does the action match the request; did the user approve it; is it riskier than stated",
      code: "Tier thresholds, the prepare-only rule, the floor callers can only raise",
    },
    tags: ["agents", "safety", "approvals", "decisions", "jev"],
    api: {
      method: "POST",
      path: "/api/v1/gate",
      priceUsd: 0.01,
      description: "Execute, confirm or escalate? An approval gate for one agent action, by risk tier.",
      inputExample: {
        action: "Email the refund confirmation to the customer",
        request: "Refund order A-104 and let the customer know",
        risk: "external",
      },
    },
  },
  {
    slug: "shonin-receipt",
    name: "Shonin Receipt",
    category: "agent-api",
    status: "beta",
    featured: true,
    oneLiner: "Proof for every agent payment: an on-chain settlement check and a signed, normalized receipt for the books.",
    pitch:
      "Receipts for AI agent payments: after an x402 payment, send the transaction or the PAYMENT-RESPONSE header and get a normalized receipt (payer, payee, token, amount, time, authorization) checked against what you expected and signed so a finance team can trust it",
    audience: ["agents", "builders", "startup", "enterprise"],
    unit: "One verified receipt for one payment",
    intake: ["The PAYMENT-RESPONSE header, or the network and transaction hash", "Optional: the payee, amount and payer you expected"],
    engine:
      "Code only: it reads the transaction from the chain, decodes the stablecoin transfer and the EIP-3009 authorization, compares them with what you expected, and signs the result.",
    rulebook: [
      "Only known stablecoins count as payments; other token transfers are ignored.",
      "A reverted or missing transaction is reported as such, never as settled.",
      "Receipts are signed over sorted-key JSON, so anyone can verify them.",
    ],
    review: "Automated: every expectation the caller sent comes back as matched or not.",
    delivery: "A JSON receipt with an explorer link, signed when a receipt key is configured.",
    turnaround: "A few seconds",
    price: {
      label: "$0.01 per receipt",
      humanAlternative: "A bookkeeper matching agent payments to block explorers by hand",
      model: "per-call",
    },
    distribution: ["x402 Bazaar, llms.txt and the agent card", "MCP registries", "x402 sellers who want receipts for their buyers", "Finance teams of companies running paying agents"],
    split: {
      llm: "Nothing",
      decide: "Nothing: receipts are exact",
      code: "Chain reads, log decoding, matching and signing",
    },
    tags: ["x402", "agents", "payments", "receipts", "accounting"],
    api: {
      method: "POST",
      path: "/api/v1/receipt",
      priceUsd: 0.01,
      description: "Proof for an agent payment: verify an x402 settlement on-chain and get a signed receipt.",
      inputExample: {
        network: "eip155:42220",
        transaction: "0xf6f71df2f84279c483b138a43c8adcfcd7c1e319459f2b1b2497cdb706a38b38",
      },
    },
  },

  // ─── Products founders run themselves ───────────────────────────────────────
  {
    slug: "gtm-harness",
    name: "GTM Harness",
    category: "product",
    status: "beta",
    featured: true,
    oneLiner: "Your go-to-market, run by agents you can check: a scorecard, sources, reviewed first messages, a 7-day sprint and a folder for Claude Code.",
    pitch:
      "A go-to-market harness for founders: describe your product and get your ideal-customer scorecard, where those customers gather, first outreach messages checked by a reviewer that can block but never send, a seven-day launch sprint, and a folder of rules and agent prompts to keep running with Claude Code",
    audience: ["startup", "builders"],
    unit: "One harness for one product",
    intake: ["Your product in one or two sentences", "Who it's for, and your goal for the month", "The channels you can use"],
    engine:
      "An LLM writes the plan and the drafts; the brain reviews every draft (ready, revise or blocked); code packs the folder, the pipeline and the Monday dashboard. The founder sends everything.",
    rulebook: [
      "The harness never sends anything; the founder does.",
      "No invented traction, numbers, customers or quotes, in the plan or in the drafts.",
      "The reviewer can block a draft but never ship one.",
      "Every edit the founder makes goes in the corrections log; repeated ones become rules.",
    ],
    review: "Every draft carries the reviewer's verdict and fixes; the founder approves new rules each Monday.",
    delivery: "A web run in about a minute, and a .zip harness folder: CLAUDE.md, scorecard, sources, rules, prompts, drafts, sprint and dashboard.",
    turnaround: "About a minute",
    price: {
      label: "Free and open source (MIT)",
      humanAlternative: "A GTM consultant's launch plan, or weeks of the founder's own time",
      model: "free",
    },
    distribution: ["Founder communities and office hours", "Startup programs and accelerators", "X threads with a live demo"],
    split: {
      llm: "The plan, the sources and the first messages",
      decide: "Whether each draft is ready, needs a revision, or is blocked",
      code: "Validation, the scorecard math, the folder, the pipeline and the dashboard",
    },
    tags: ["gtm", "founders", "agents", "claude-code", "open-source"],
    links: [{ label: "Run it", href: "/gtm" }],
  },

  // ─── Services: sell the finished work ────────────────────────────────────────
  {
    slug: "agent-ready-website",
    name: "Agent-Ready Website",
    category: "service",
    status: "live",
    featured: true,
    oneLiner: "Your website upgraded so customers and AI assistants can both get answers and buy.",
    pitch:
      "Upgrade the website of a restaurant, shop, clinic or farm with an AI concierge on WhatsApp and web chat that answers customer questions, handles ordering and bookings, sends payment links, and publishes agent-readable pages so AI assistants can recommend and buy from the business",
    audience: ["smb"],
    unit: "One website upgraded (up to 10 pages) plus a concierge trained on your business",
    intake: [
      "Website URL and admin access",
      "Price list, FAQs and policies (PDF, doc or photos are fine)",
      "WhatsApp Business number",
      "How customers pay today: transfer, Paystack or MiniPay",
    ],
    engine:
      "An LLM drafts the concierge's knowledge base from your own documents; the decision brain routes every customer message (order, booking, question, complaint, human) and scores urgency.",
    rulebook: [
      "Never quote a price that isn't on the client's price list; hand it to a person instead.",
      "Answers about hours, location or delivery quote the client's own policy text.",
      "Complaints and refund requests reach a person within 10 minutes in business hours.",
      "A booking is confirmed only after code checks the slot against the calendar.",
      "Payments are links the customer taps; the concierge never asks for card or bank details in chat.",
      "The concierge only handles this business's own questions, orders and bookings: WhatsApp's Business API has banned general-purpose AI chatbots since January 2026.",
    ],
    review: "The owner approves every new answer before it goes live; conversations below 0.7 confidence are flagged daily.",
    delivery: "Live site, WhatsApp concierge, and a weekly WhatsApp summary of what customers asked.",
    turnaround: "5 working days",
    price: {
      label: "From $200 + $25/month care",
      ngn: "₦300,000 + ₦35,000/month",
      humanAlternative: "A receptionist or social-media handler at ₦150,000–₦250,000 a month, plus an agency redesign at ₦1M+",
      model: "retainer",
    },
    checkout: { amountUsd: 100, label: "50% deposit on the website setup ($200)" },
    distribution: [
      "Upsell existing client sites first: farms, fashion houses, churches, foundations, restaurants",
      "A 60-second before/after demo per niche",
      "WhatsApp status and reels showing real (consented) customer conversations",
    ],
    split: {
      llm: "Writes answers and follow-ups from the client's own documents",
      decide: "Routes each message: order, booking, question, complaint or person; scores urgency",
      code: "Checks the calendar, creates payment links, sends notifications",
    },
    tags: ["whatsapp", "website", "concierge", "smb", "nigeria"],
  },
  {
    slug: "agent-readiness-audit",
    name: "Agent Readiness Audit",
    category: "service",
    status: "live",
    featured: true,
    firstJobFree: true,
    oneLiner: "Every workflow in your business split into what AI writes, what it decides and what code does, with the savings.",
    pitch:
      "A fixed-scope audit of a business's operations that finds which tasks AI agents can take over, what it will cost, what it will save, and a 30-day plan to ship the first agent",
    audience: ["smb", "startup", "enterprise"],
    unit: "One audit report covering up to 12 workflows",
    intake: [
      "A 45-minute recorded walkthrough of how the work gets done",
      "The tools you use: WhatsApp, Excel, Slack, CRM, bank apps",
      "Monthly volumes: messages, orders, invoices, tickets",
      "Who approves what",
    ],
    engine:
      "Agents transcribe and decompose each workflow into steps; the decision brain classifies each step as LLM, typed decision, code or human, and scores automation value and risk.",
    rulebook: [
      "Every recommendation names the step, the tool, the monthly volume and the cost per unit before and after.",
      "Anything that moves money or can't be undone is marked prepare-then-approve, never fully automated.",
      "No savings claim without a volume number from the client; show the formula.",
      "Recommend a tool the client already pays for before recommending a build.",
      "The first recommended agent must be shippable in under 14 days.",
    ],
    review: "The founder reviews every audit line by line before delivery.",
    delivery: "An interactive report page, a 20-minute recorded walkthrough, and a 30-day build plan.",
    turnaround: "72 hours after the walkthrough",
    price: {
      label: "$490 per audit (SMEs: ₦150,000)",
      ngn: "₦150,000 for SMEs",
      humanAlternative: "Management consultants charge $3,000–$10,000 for a digital transformation assessment",
      model: "per-unit",
    },
    checkout: { amountUsd: 490, label: "One Agent Readiness Audit" },
    distribution: [
      "First five audits free for design partners, in exchange for a case study",
      "Offered at the end of every workshop and talk",
      "Outbound to SME owners in Lagos, Accra and Nairobi with a sample audit attached",
    ],
    split: {
      llm: "Transcribes the walkthrough and writes the report",
      decide: "Classifies each step (LLM, decision, code, human) and scores automation value and risk",
      code: "Computes volumes, costs, savings and payback",
    },
    tags: ["audit", "strategy", "roi", "jev"],
  },
  {
    slug: "company-brain",
    name: "Company Brain",
    category: "service",
    status: "beta",
    featured: true,
    oneLiner: "An AI teammate in your Slack or WhatsApp groups that remembers decisions, answers questions, and knows when to stay quiet.",
    pitch:
      "Deploy an AI teammate into a company's Slack or WhatsApp groups that remembers company knowledge and decisions, answers staff questions, investigates, asks for approval before consequential actions, and stays quiet when it has nothing useful to add",
    audience: ["startup", "smb", "enterprise"],
    unit: "One deployed brain for one organization, plus monthly care",
    intake: [
      "Slack workspace admin, or a WhatsApp Business API number",
      "Channels it may read and speak in, and how proactive to be in each",
      "Documents and wikis to learn from",
      "Actions that need approval: emails, payments, deletions",
      "Your Cloudflare account (you own the data), or we host",
    ],
    engine:
      "Built on Supermemory's open-sourced company-brain harness (Apache-2.0, Cloudflare Agents SDK). We move its triage, turn gate and approval classifier onto a System One model: 18 typed questions per message in one ~0.3 s call, with the LLM kept for anything it isn't sure of. Your model and infrastructure costs (about $150–300/month for a 30-person team) are billed to your own accounts.",
    rulebook: [
      "Silence is a valid outcome: an investigation that finds nothing posts nothing.",
      "Private channels and DMs never leak into shared answers; memory is scoped per channel and person.",
      "Anything that emails a customer, moves money or deletes data waits for an Approve click.",
      "A newer message that replaces the request stops the old work instead of finishing it.",
      "Live facts (issue status, balances, deploys) come from the connected app, not from memory.",
      "Lock /setup behind Cloudflare Access at deploy: whoever signs in first owns the deployment.",
      "One memory account per customer: memory tags are global inside an account.",
    ],
    review: "Weekly review of every approval, every pass and a sample of answers; thresholds tuned per channel.",
    delivery: "The brain live in your workspace, an admin view of the decision log, and a monthly usage report.",
    turnaround: "7 days to first answers",
    price: {
      label: "$3,500 setup + $900/month care",
      ngn: "₦1,200,000 setup + ₦300,000/month (SMEs)",
      humanAlternative: "An operations or knowledge manager at $1,000–$5,000 a month",
      model: "retainer",
    },
    checkout: { amountUsd: 1750, label: "50% deposit on setup ($3,500)" },
    distribution: [
      "Live demo in our own workspace on every sales call",
      "Seed to Series A teams in Lagos, Nairobi and remote-first companies",
      "Web3 foundations and ecosystem teams running builder communities",
    ],
    split: {
      llm: "Writes answers, summaries and investigation reports",
      decide: "Triage (answer, investigate, react, pass), turn gate (ignore, append, replace, stop), approval needed",
      code: "Permissions, memory scopes, budgets, checkpoints, retries",
    },
    tags: ["slack", "whatsapp", "memory", "cloudflare", "jev"],
    links: [{ label: "Upstream harness", href: "https://github.com/supermemoryai/company-brain" }],
  },
  {
    slug: "grant-desk",
    name: "Grant & RFP Desk",
    category: "service",
    status: "live",
    featured: true,
    oneLiner: "Grant applications and RFP responses scored against the funder's rubric before a reviewer ever sees them.",
    pitch:
      "We write, review and score grant applications, RFP responses and funding proposals for startups, builders, NGOs and foundations, against the funder's rubric, with evidence for every claim",
    audience: ["startup", "builders", "ecosystems"],
    unit: "One submission-ready application",
    intake: [
      "The program link and its rubric or requirements",
      "Your repo, demo and any traction data",
      "Team, budget and milestones (rough is fine)",
      "The deadline",
    ],
    engine:
      "The brain scores the draft against every rubric criterion in one pass and names the weakest three; an LLM rewrites those sections with the evidence you supplied.",
    rulebook: [
      "Every number links to evidence: a dashboard, an explorer link, a repo or a signed letter.",
      "Milestones are dated, measurable and tied to budget lines.",
      "We never invent traction, users or partners; missing evidence becomes a milestone instead.",
      "Use the funder's language for their priorities, but never paste their text back at them.",
      "Conflict rule: no applications to programs where anyone on our team reviews or allocates funds.",
    ],
    review: "A person reads every application end to end before handover.",
    delivery: "A submission-ready document, a rubric scorecard, and an attachments checklist.",
    turnaround: "3 working days (48-hour rush available)",
    price: {
      label: "$350 per grant application · $1,200 per RFP",
      ngn: "₦250,000 per application",
      humanAlternative: "Freelance grant writers charge $1,000–$5,000 per proposal",
      model: "per-unit",
    },
    checkout: { amountUsd: 350, label: "One grant application" },
    distribution: [
      "Builder communities and hackathon Telegram groups",
      "Free rubric score for any public application (lead magnet, via the Grant Fit API)",
      "Accelerators and hubs that push their founders to apply",
    ],
    split: {
      llm: "Rewrites weak sections using the evidence provided",
      decide: "Scores each rubric criterion, eligibility, readiness and unsupported claims",
      code: "Checks word limits, deadlines, links and attachments",
    },
    tags: ["grants", "rfp", "proposals", "funding"],
  },
  {
    slug: "agent-launch-sprint",
    name: "Agent Launch Sprint",
    category: "service",
    status: "live",
    featured: true,
    oneLiner: "One production AI agent for one workflow, shipped in 10 working days by a forward-deployed engineer.",
    pitch:
      "A forward-deployed engineer builds and deploys a custom AI agent for one business workflow, such as customer support, lead qualification, bookings, collections or reporting, on WhatsApp, Telegram, Slack or the web",
    audience: ["startup", "smb", "enterprise"],
    unit: "One agent in production for one workflow",
    intake: [
      "The workflow, its volume, and who does it today",
      "Access to the systems it touches (read-only first)",
      "What correct looks like, with 20 real examples",
      "Approval rules",
    ],
    engine:
      "Claude-class models for generation, a System One model for every routing and approval decision, plain code for anything exact; evals built from your 20 examples before launch.",
    rulebook: [
      "No launch without an eval set built from real examples and a pass rate agreed in writing.",
      "Every tool that writes, sends or pays has an approval path and a spend limit.",
      "Every decision is logged with model version, probabilities and confidence.",
      "Ship read-only first; add write actions one at a time behind approvals.",
      "Handover includes a runbook a non-engineer can follow.",
    ],
    review: "The client approves eval results before go-live; we read the decision log daily for two weeks.",
    delivery: "Agent live on your channel, eval report, decision dashboard, runbook, 14 days of hypercare.",
    turnaround: "10 working days",
    price: {
      label: "From $2,500 per agent",
      ngn: "From ₦2,000,000",
      humanAlternative: "Dev agencies quote $10,000–$30,000 and two to three months",
      model: "per-unit",
    },
    checkout: { amountUsd: 1250, label: "50% deposit on one agent ($2,500)" },
    distribution: [
      "Audits convert into sprints",
      "Case-study threads with real metrics",
      "Referrals from ecosystem partners and accelerators",
    ],
    split: {
      llm: "Drafts replies, summaries and documents",
      decide: "Routes, scores, approves and escalates",
      code: "Calls APIs, prepares payments, writes records, sends notifications",
    },
    tags: ["agents", "fde", "whatsapp", "telegram", "evals"],
  },
  {
    slug: "ai-visibility-audit",
    name: "AI Visibility Audit",
    category: "service",
    status: "live",
    featured: true,
    firstJobFree: true,
    oneLiner: "What ChatGPT, Claude and Gemini say about your business today, and the fixes that change the answer.",
    pitch:
      "An audit of what AI assistants like ChatGPT, Claude, Gemini and Perplexity say about a business when customers ask them, with fixes to the website, listings and agent-readable pages so AI recommends the business accurately",
    audience: ["smb", "startup"],
    unit: "One audit: 25 buyer questions across 4 assistants",
    intake: ["Business name and website", "Five competitors", "Top products or services", "Cities you serve"],
    engine:
      "Agents ask each assistant 25 buyer-style questions; the brain scores every answer for accuracy, sentiment and whether you were recommended; an LLM writes the fixes.",
    rulebook: [
      "Every finding shows the exact question, the assistant, the date and the answer it gave.",
      "Accuracy is judged against the business's own published facts, not guesses.",
      "Fixes are things the owner controls: website copy, llms.txt, structured data, listings, reviews.",
      "The same 25 questions are re-run monthly, so progress is measured, not claimed.",
    ],
    review: "A person checks every answer flagged as inaccurate before it goes in the report.",
    delivery: "A report page with every answer quoted, a ranked fix list, and optional monthly tracking.",
    turnaround: "48 hours",
    price: {
      label: "$150 per audit · tracking $25/month",
      ngn: "₦60,000 · tracking ₦25,000/month",
      humanAlternative: "SEO and PR retainers from ₦300,000 a month that never measure what AI says",
      model: "per-unit",
    },
    checkout: { amountUsd: 150, label: "One AI Visibility Audit" },
    distribution: [
      "Run it free on a prospect and send the screenshot: here is what ChatGPT says about you today",
      "Bundle with the Agent-Ready Website",
      "Business owner groups, chambers and markets",
    ],
    split: {
      llm: "Writes the fixes and new page copy",
      decide: "Scores accuracy, sentiment and recommended-or-not for every answer",
      code: "Asks on schedule, stores answers, diffs month over month",
    },
    tags: ["ai-search", "visibility", "geo", "smb"],
  },
  {
    slug: "agent-reliability-audit",
    name: "Agent Reliability Audit",
    category: "service",
    status: "live",
    featured: true,
    oneLiner: "Before your agent touches customers or money: consistency, robustness, calibration and safety, measured.",
    pitch:
      "An independent reliability audit of an AI agent or automated decision system before launch or for a regulator: consistency across repeated runs, robustness to reworded and adversarial inputs, calibration of its confidence, and safety checks for data leaks and destructive actions",
    audience: ["startup", "enterprise"],
    unit: "One agent workflow audited",
    intake: [
      "Sandbox access to the agent",
      "The workflow and what can go wrong",
      "Real or synthetic test cases",
      "Rules that apply: NDPA and CBN circulars, Ghana's data protection drafts, the EU AI Act, FCA or RBI guidance",
    ],
    engine:
      "A harness modelled on Princeton's agent-reliability work: repeated runs, reworded prompts, simulated tool outages, prompt-injection suites, leak and destructive-action checks. The brain grades every trace.",
    rulebook: [
      "Every finding is reproducible from a saved trace.",
      "Calibration is measured: does 0.9 confidence mean right nine times in ten?",
      "Every automated decision can be explained and contested, as regulators are starting to require.",
      "Destructive and money-moving actions are tested in a sandbox only.",
    ],
    review: "A senior engineer signs every report.",
    delivery: "Scores per dimension, failing traces, fixes, and a re-test after you fix them.",
    turnaround: "5–10 working days",
    price: {
      label: "From $3,000 per workflow",
      ngn: "From ₦2,500,000",
      humanAlternative: "Big-4 AI assurance engagements start at $25,000",
      model: "per-unit",
    },
    checkout: { amountUsd: 1500, label: "50% deposit on one workflow ($3,000)" },
    distribution: [
      "Fintechs facing the CBN's automated AML requirement",
      "Startups selling agents to banks and telcos",
      "Regulatory sandboxes and innovation hubs",
    ],
    split: {
      llm: "Generates adversarial variants and writes the report",
      decide: "Grades each trace: correct, consistent, safe, calibrated",
      code: "Runs the harness, repeats, simulates outages, computes metrics",
    },
    tags: ["evals", "reliability", "compliance", "princeton"],
  },
  {
    slug: "aml-alert-triage",
    name: "AML Alert Triage",
    category: "service",
    status: "beta",
    oneLiner: "AML alerts triaged and suspicious-transaction reports drafted, with an analyst deciding every filing.",
    pitch:
      "Triage of anti-money-laundering transaction monitoring alerts for fintechs, banks and payment companies: score each alert, close obvious false positives with evidence, and draft suspicious transaction reports for an analyst to approve",
    audience: ["startup", "enterprise"],
    unit: "One alert triaged",
    intake: ["Alert export and rule definitions", "Customer risk tiers", "500+ past dispositions", "Your STR template"],
    engine:
      "Code assembles each alert's transactions and customer profile; the brain scores risk and decides close or escalate; an LLM drafts the STR narrative for an analyst to approve.",
    rulebook: [
      "The model never files a report; an analyst approves every STR.",
      "Every closure cites the transactions and the rule that clears it.",
      "Amounts, dates and velocities are computed in code, never by a model.",
      "Model version and confidence are logged per alert for the examiner.",
    ],
    review: "Analysts review every escalation and a random 10% of closures.",
    delivery: "Dispositions and STR drafts in your case manager, with an audit log.",
    turnaround: "Same day",
    price: {
      label: "$0.40 per alert",
      humanAlternative: "About $1 of analyst time per alert",
      model: "per-unit",
    },
    distribution: [
      "Compliance leads at fintechs facing the CBN's automated AML requirement",
      "Case-management vendors as partners",
      "Agent Reliability Audit clients",
    ],
    split: {
      llm: "Drafts STR narratives",
      decide: "Risk score; close or escalate",
      code: "Assembles transactions, computes amounts and velocities, logs",
    },
    tags: ["aml", "compliance", "fintech", "nigeria"],
  },
  {
    slug: "creative-packs",
    name: "Weekly Creative Pack",
    category: "service",
    status: "live",
    oneLiner: "A week of on-brand posts, reel scripts and WhatsApp catalog updates, delivered every Monday.",
    pitch:
      "Weekly Instagram, TikTok and WhatsApp content for fashion, food, beauty and agro brands: product posts, captions, reel scripts and catalog updates in the brand's own voice, and the owner signs off on every post",
    audience: ["smb"],
    unit: "One weekly pack for one brand",
    intake: ["Brand kit and 10 past posts you like", "Product photos and prices", "This week's offers"],
    engine:
      "An LLM drafts in the brand's voice from its own past posts; the brain gates each draft (hook, specificity, voice, unsourced claims) before the owner sees it.",
    rulebook: [
      "Never invent prices, discounts or stock.",
      "Every post matches the brand's past voice, or it doesn't ship.",
      "The owner approves the pack before anything is posted.",
    ],
    review: "Owner approval on WhatsApp every week.",
    delivery: "A shared folder and a WhatsApp preview every Monday.",
    turnaround: "Weekly",
    price: {
      label: "$49/month (4 packs)",
      ngn: "₦60,000/month",
      humanAlternative: "A social media manager at ₦150,000–₦300,000 a month",
      model: "retainer",
    },
    checkout: { amountUsd: 49, label: "First month: 4 packs" },
    distribution: ["Existing website clients", "DMs to brands with strong products and weak feeds", "Market and trade associations"],
    split: {
      llm: "Drafts posts, captions and scripts",
      decide: "Content gate: hook, specificity, voice, unsourced claims",
      code: "Scheduling and catalog sync",
    },
    tags: ["content", "social", "smb", "whatsapp"],
  },
  {
    // Soon until it has shipped our own shows first (company/ops/playbooks/video-desk.md).
    slug: "video-desk",
    name: "Video Desk",
    category: "service",
    status: "soon",
    oneLiner: "One long recording in; captioned clips, a trailer, chapters and a tighter cut out, and you approve every clip.",
    pitch:
      "Video editing for creators, founders, podcasts and communities: turn a long recording such as a podcast, livestream, workshop, tutorial or community call into captioned vertical clips for X, TikTok, Instagram Reels and YouTube Shorts, a highlight trailer, YouTube chapters and a tightened long-form edit, with the owner approving every clip",
    audience: ["builders", "startup", "ecosystems", "smb"],
    unit: "One recording of up to 60 minutes: 8 captioned vertical clips, a trailer of up to 60 seconds, YouTube chapters and a tightened long-form cut",
    intake: [
      "The recording or a link to it, plus the transcript if your recording tool exports one",
      "Who speaks, with names spelled right, and a publishing release from every guest",
      "A glossary: products, tickers, people and places to spell right",
      "Brand kit: logo, colours, intro or outro, and any music you have a licence for",
      "Where the clips will run: X, TikTok, Reels, Shorts or LinkedIn",
    ],
    engine:
      "Code transcribes the recording with word timings (Whisper), cuts it into candidate moments on sentence boundaries and finds the pauses and fillers; the decision brain scores every moment for hook, payoff and whether it stands alone, and flags money claims and private details; code reframes to 9:16, burns in captions, levels the audio and renders; an LLM writes titles, post copy and chapter names.",
    rulebook: [
      "A clip starts on the first word of a sentence and ends on the last word of a finished thought; code snaps every cut to word timings.",
      "Cuts remove pauses, fillers and retakes, never words that change what was said. A trailer may reorder whole sentences but never splices words into new ones.",
      "A person checks names, products and numbers in the captions against the client's glossary before a clip ships; the glossary also goes into the transcriber's prompt.",
      "Money, health or legal claims, and private details said aloud (phone numbers, addresses, seed phrases), go to a person before a clip ships, whatever its score.",
      "Guests appear only in clips from recordings they agreed to publish.",
      "Music, B-roll and logos come only from the client's own library or licensed sources.",
      "Clips run 140 seconds or less, so one file posts to X without Premium, Shorts, Reels, TikTok and LinkedIn (research/video-editing.md).",
      "Audio is measured in code: -14 LUFS integrated and a true peak at or under -1 dBTP in the delivered file.",
      "The client approves every clip and posts it; we never post from a client's account.",
    ],
    review: "The owner watches every draft clip and approves, trims, reframes or rejects it; nothing ships without a named approval, and every trim goes into the rulebook log.",
    delivery: "Vertical MP4s with burned-in captions, SRT files, the trailer, the tightened cut, YouTube chapters and post copy, in a shared folder with the review sheet.",
    turnaround: "48 hours per recording",
    price: {
      label: "$200 per recording (up to 60 min)",
      ngn: "₦100,000 per recording",
      humanAlternative:
        "Editors charge $484–$1,675 for a long-form cut plus nine short pieces; in Lagos, recording and editing a one-hour video episode costs ₦250,000–₦400,000",
      model: "per-unit",
    },
    distribution: [
      "Our own shows first: CeloIQ Sessions and Based Conversations, 3 or more clips per episode",
      "Ecosystem teams that record community calls, workshops and Spaces",
      "A free clip pack cut from one public episode, sent to the host as the sample",
    ],
    split: {
      llm: "Writes titles, post copy and chapter names",
      decide: "Scores each candidate moment: hook, payoff, stands alone, kind, money claims, private details",
      code: "Transcribes, cuts on word timings, removes pauses and fillers, reframes, captions, levels audio, checks lengths",
    },
    tags: ["video", "clips", "podcast", "captions", "content"],
  },
  {
    // Soon until it has shipped 5 shorts from our own posts (company/ops/playbooks/explainer-shorts.md).
    slug: "explainer-shorts",
    name: "Explainer Shorts",
    category: "service",
    status: "soon",
    oneLiner: "A topic and your sources in; a 30–60 second vertical explainer out, every fact quoted from a source and approved by you.",
    pitch:
      "Short-form explainer videos for founders, product teams, ecosystems and creators: turn a doc, blog post, changelog or research note into a sourced 30–60 second vertical video for TikTok, Instagram Reels, YouTube Shorts and X, with an AI voiceover (Nigerian English available), captions, on-screen headlines, brand visuals or licensed stock footage, and a claim-to-source list the owner approves",
    audience: ["builders", "startup", "ecosystems", "smb"],
    unit: "One short: 30–60 seconds at 1080×1920, from one topic and sources you own or may use, with one revision round",
    intake: [
      "The topic, and the sources the short may draw on: docs, posts, changelogs or research you own or may use",
      "Names, products, tickers and places, spelled right, with how each one is said",
      "Brand kit: logo, colours, and any footage or music you hold a licence for",
      "Where it will run (TikTok, Reels, Shorts or X) and the one call to action",
    ],
    engine:
      "An LLM writes the script from your sources: a hook, one idea, on-screen text, and every fact with a quote copied from its source; code checks every length, quote and number said aloud; the decision brain runs the content gate and checks each claim against its quote; code voices it with a licensed voice (Azure's Nigerian English voices by default), lays the beats on whole frames, burns in captions and headlines, adds brand visuals, licensed stock or animated scenes for figures, code and flows (HyperFrames, rendered frame by frame), ducks a licensed music bed, levels the audio and writes the publish packet.",
    rulebook: [
      "A script is written from the client's sources, never from a topic alone. Every factual sentence carries a quote that code finds word for word in its source.",
      "Every number said aloud appears in that beat's quotes; a miss blocks the short until a person fixes it. A person checks names against the client's glossary and listens to each one.",
      "What's on screen follows the same rule. A figure in a scene appears in that beat's quotes, and a line of code appears in a source word for word. The writer fills a scene's data and never writes HTML.",
      "Each short ships with a claim-to-source list: every beat's narration, the passage each fact rests on, and the page or URL.",
      "The voice has a commercial licence, recorded with its provider and voice: no edge-tts or other unofficial endpoint, no ElevenLabs Free, no local engine outside the allowlist of commercially licensed weights, so never OmniVoice, VoiceStudio's non-commercial default (research/explainer-shorts.md §6, research/voicestudio.md §3).",
      "The post says the voice is AI, and the publish packet switches on YouTube's altered-or-synthetic setting, TikTok's AI-generated label and Meta's AI info label; code checks both before approval.",
      "An AI narrator is never presented as a human expert. Health, money, legal and political shorts name the human or institutional source and go to a person, whatever their score.",
      "Stock footage comes only from Pexels or Pixabay, logged clip by clip with provider, id, page, creator and download date. No identifiable person in a short about health, crime or debt, and no third-party logo in a stock shot.",
      "Music comes only from the client's licensed library, Pixabay Music with its certificate saved, or a paid library licensed for every platform; never TikTok's or Meta's business libraries in a master, never commercial releases.",
      "Every short puts at least one sourced number, name or date on screen, and one client's shorts vary hook, structure and footage. A short is never a verbatim reading of a page.",
      "Audio is measured in code: -14 LUFS integrated and a true peak at or under -1 dBTP; captions run from the first spoken word to the last.",
      "The client approves every short by name against the exact script that was rendered, and posts it; we never post from a client's account.",
    ],
    review:
      "A person watches each short with the sound on and off, reads every claim the brain flags against its source, listens to every name, and approves by name; an edit after the render needs a new render and a new approval.",
    delivery:
      "A vertical MP4 with burned-in captions, an SRT file, a cover frame, post copy with the AI disclosure, and a publish packet with the platform AI labels, the claim-to-source list and the licence ledger.",
    turnaround: "24 hours per short",
    price: {
      label: "$75 per short · $720 for 12 a month",
      ngn: "₦35,000 per short · ₦360,000 for 12 a month",
      humanAlternative:
        "A freelancer scripts, voices and edits a 30–60 second explainer for $130–$550, Fiverr's guide puts one at $200–$400, and agencies charge $1,000–$3,000; in Nigeria a social-media animation costs ₦50,000–₦150,000",
      model: "per-unit",
    },
    distribution: [
      "Our own channel first: one short from each Shonin research post, 5 before the offer opens",
      "Ecosystem teams and startups that ship docs, changelogs and launches every month",
      "A free short made from one of the prospect's public posts, sent to them as the sample",
    ],
    split: {
      llm: "Writes the script from the sources: narration, on-screen text, visuals, claims with quotes, the post",
      decide: "Runs the content gate on the draft and checks each claim against its quote: ok, check or cut",
      code: "Checks lengths, quotes and numbers; voices, times beats to whole frames, captions, visuals, music ducking, loudness; gates approval on the voice licence and the AI labels",
    },
    tags: ["video", "shorts", "explainer", "content", "captions"],
  },
  {
    slug: "decision-router-retrofit",
    name: "Decision Router Retrofit",
    category: "service",
    status: "beta",
    oneLiner: "We move the routing, scoring and approval calls in your agents off frontier models, and take a share of what you save.",
    pitch:
      "For AI startups and teams with a large LLM bill: find every decision agents make with a frontier model (routing, classification, scoring, approvals) and move it to a System One model or plain code, with cost and accuracy measured on the team's own traffic",
    audience: ["startup", "enterprise"],
    unit: "One agent or pipeline retrofitted",
    intake: [
      "Read access to agent code and a week of traces or logs",
      "Current monthly model spend by route",
      "The accuracy bar for each decision",
    ],
    engine:
      "We replay your logged traffic through the new decision layer, compare answers and cost, and switch only the routes that hold accuracy.",
    rulebook: [
      "Measure on your traffic, never on vendor benchmarks.",
      "A route moves only when agreement with the old answer clears the agreed bar on a held-out sample.",
      "Every moved route logs model version, probabilities and confidence.",
      "Thresholds are set per action, scaled to what being wrong costs.",
      "Anything that counts, sums or compares dates moves to code, not to a model.",
    ],
    review: "The client signs off on the replay report before any route switches.",
    delivery: "A pull request, a replay report with cost and agreement per route, and a monitoring view.",
    turnaround: "2 weeks",
    price: {
      label: "20% of the first 6 months of measured savings (min $750)",
      humanAlternative: "An ML engineer's month at $8,000–$20,000",
      model: "share-of-savings",
    },
    distribution: [
      "Public teardowns: how much a real agent's bill dropped and why",
      "A free savings estimate from one week of logs",
      "AI builder communities and hackathons",
    ],
    split: {
      llm: "Keeps only the routes that generate text",
      decide: "Takes over routing, classification, scoring and approvals",
      code: "Takes over counting, dates, limits and exact rules",
    },
    tags: ["jev", "cost", "llm-ops", "evals"],
  },
  {
    slug: "support-triage",
    name: "Support Triage Desk",
    category: "service",
    status: "beta",
    oneLiner: "Every support message classified and routed in under a second; refunds and angry customers always reach a person.",
    pitch:
      "Automatic triage and routing of customer support messages for fintechs, e-commerce and apps: classify the request, score frustration and complexity, send simple lookups to code, draft replies for the rest, and escalate refunds and angry customers to a person",
    audience: ["startup", "smb"],
    unit: "Per 1,000 messages triaged",
    intake: [
      "Support channels: email, WhatsApp, in-app",
      "Categories and who owns each",
      "Refund and escalation policy",
      "500 past tickets to calibrate against",
    ],
    engine: "One System One call per message (intent, complexity, frustration, refund requested) routes it to code, a specialist LLM, or a person.",
    rulebook: [
      "Refunds are prepared and approved by a person, always.",
      "A very angry customer reaches a person first, whatever the category.",
      "Order-status questions are answered by code from the order system, never by a model.",
      "Pidgin and local-language messages route as reliably as English, or go to a person.",
    ],
    review: "Weekly audit of 50 random routes; every misroute becomes a rulebook entry.",
    delivery: "Routing live in your helpdesk, plus a weekly misroute report.",
    turnaround: "5 days to live",
    price: {
      label: "$250 setup + $25 per 1,000 messages",
      humanAlternative: "Triaging by hand: $400–$1,500 a month per support agent",
      model: "per-unit",
    },
    checkout: { amountUsd: 250, label: "Setup" },
    distribution: ["Fintech and e-commerce operators", "Helpdesk vendors as partners", "The Triage API for agent builders"],
    split: {
      llm: "Drafts replies for the specialist routes",
      decide: "Intent, complexity, frustration, refund requested",
      code: "Order lookups, SLAs, assignment",
    },
    tags: ["support", "fintech", "triage", "jev"],
    links: [{ label: "Triage API", href: "/directory/triage-api" }],
  },
  {
    slug: "team-ai-upskilling",
    name: "Team AI Upskilling",
    category: "service",
    status: "live",
    oneLiner: "A four-week, hands-on program that gets a team shipping its first internal agent.",
    pitch:
      "Corporate AI training for a company's staff: a four-week hands-on program on AI tools, prompting, agents and responsible AI in which the team builds and ships its own first internal agent",
    audience: ["enterprise", "smb", "ecosystems"],
    unit: "One cohort of up to 20 staff, four weeks",
    intake: ["Team roles and tools", "Two workflows to automate as capstones", "Data and AI policies", "Preferred schedule"],
    engine:
      "The AI Study Group curriculum (agentic AI engineering and ethical AI in Africa) adapted to the team; placement and grading run through the decision brain.",
    rulebook: [
      "Every participant ships something by week four, or the team gets a free extra week.",
      "Capstones use the company's real workflows, with its data policies applied.",
      "The responsible-AI session covers Nigeria's NDPA (or local law) and the company's own policy.",
      "Progress is measured in shipped artifacts, not attendance.",
    ],
    review: "A facilitator reviews every capstone; managers get a weekly progress note.",
    delivery: "Live sessions, labs, a certificate per participant (optionally onchain), and the shipped capstone agents.",
    turnaround: "4 weeks",
    price: {
      label: "$4,000 per cohort of 20",
      ngn: "₦3,500,000 per cohort",
      humanAlternative: "Corporate training firms charge $300–$1,000 per seat for slide-deck courses",
      model: "cohort",
    },
    checkout: { amountUsd: 2000, label: "50% deposit on a cohort of 20 ($4,000)" },
    distribution: [
      "HR and L&D leads at banks, telcos, agencies and NGOs",
      "Tech hubs and chambers of commerce",
      "Study Group alumni inside those companies",
    ],
    split: {
      llm: "Generates exercises, feedback and examples",
      decide: "Places learners, grades short answers, flags who is falling behind",
      code: "Schedules, tracks progress, issues certificates",
    },
    tags: ["training", "enterprise", "upskilling"],
  },
  {
    slug: "minipay-launch",
    name: "MiniPay Mini App Launch",
    category: "service",
    status: "beta",
    oneLiner: "Put your business inside MiniPay: a stablecoin mini app your customers can pay from, shipped in two weeks.",
    pitch:
      "Build and launch a MiniPay Mini App for a business or brand so customers can pay in stablecoins inside the MiniPay wallet, with an AI assistant, loyalty or payment features",
    audience: ["smb", "startup"],
    unit: "One Mini App launched",
    intake: ["What customers should be able to do in the app", "Brand assets", "Payout wallet and off-ramp preference", "Launch date"],
    engine: "A MiniPay starter kit (Next.js, viem, fee abstraction) plus an optional agent that answers customers and prepares payments.",
    rulebook: [
      "Payments are always started by the customer's own tap in MiniPay; agents only prepare them.",
      "Test on Celo Sepolia before mainnet and publish contract addresses.",
      "Works on low-end Android phones and slow networks.",
      "Conflict rule: builders we support in an ecosystem role get free guidance, not paid builds.",
    ],
    review: "Code review and a mainnet checklist before launch.",
    delivery: "Live Mini App, source code, and a handover call.",
    turnaround: "2 weeks",
    price: {
      label: "From $1,500",
      ngn: "From ₦1,200,000",
      humanAlternative: "Web3 dev shops charge $8,000–$25,000",
      model: "per-unit",
    },
    checkout: { amountUsd: 750, label: "50% deposit ($1,500)" },
    distribution: [
      "Brands and SMEs selling to mobile-first stablecoin users",
      "Demo apps for restaurants, events and savings groups",
      "Hackathon teams that need production help",
    ],
    split: {
      llm: "Drafts copy and in-app assistant answers",
      decide: "Routes customer requests and flags risky payment intents",
      code: "Contracts, payments, fee abstraction",
    },
    tags: ["celo", "minipay", "stablecoins", "web3"],
  },
  {
    slug: "afcfta-trade-desk",
    name: "AfCFTA Trade Desk",
    category: "service",
    status: "soon",
    oneLiner: "HS-code classification and export paperwork checks for African exporters, per shipment.",
    pitch:
      "Classify products into HS tariff codes and check export documents and rules of origin for exporters trading across African borders under AfCFTA",
    audience: ["smb", "enterprise"],
    unit: "One shipment classified and checked",
    intake: ["Product descriptions, photos and specs", "Origin and destination countries", "Commercial invoice and packing list"],
    engine:
      "Code narrows candidate HS codes from the tariff schedule; the brain picks between finalists and flags documents that don't match; a licensed agent signs off.",
    rulebook: [
      "Codes are narrowed from the official tariff schedule in code before any model picks between finalists.",
      "Low-confidence classifications go to a licensed customs agent.",
      "Every document mismatch cites the field and the rule.",
    ],
    review: "A licensed customs broker reviews every classification until accuracy is proven per product line.",
    delivery: "Classification memo, document checklist and flagged issues.",
    turnaround: "24 hours",
    price: {
      label: "$25 per shipment",
      ngn: "₦20,000 per shipment",
      humanAlternative: "Customs brokers charge $50–$200 per classification",
      model: "per-unit",
    },
    distribution: ["Exporter associations and trade hubs", "Freight forwarders as partners", "AfCFTA support programs"],
    split: {
      llm: "Turns product specs into tariff language",
      decide: "Picks between candidate HS codes; flags mismatched documents",
      code: "Narrows candidates from the schedule; checks totals and dates",
    },
    tags: ["trade", "afcfta", "customs", "exporters"],
  },
  {
    slug: "kyc-precheck",
    name: "KYC File Pre-check",
    category: "service",
    status: "soon",
    oneLiner: "Every onboarding file checked for completeness and consistency before a compliance officer opens it.",
    pitch:
      "Pre-check customer onboarding and KYC files for fintechs, cooperatives and microfinance banks: missing documents, mismatched names and dates, and expired IDs, before a compliance officer reviews them",
    audience: ["startup", "enterprise"],
    unit: "One onboarding file pre-checked",
    intake: ["Your KYC policy and tiers", "Accepted document types", "100 anonymized sample files"],
    engine:
      "Code extracts fields and compares names and dates; the brain answers typed questions about document type and legibility; people decide.",
    rulebook: [
      "Name and date comparisons happen in code, never in a model.",
      "The model never approves a customer; it only flags.",
      "Files are processed in-region and deleted after the retention period.",
    ],
    review: "A compliance officer makes every final decision.",
    delivery: "A pre-check result per file in your back office.",
    turnaround: "Real time",
    price: {
      label: "$1 per file",
      ngn: "₦800 per file",
      humanAlternative: "Compliance analysts review 40–80 files a day at $600–$1,500 a month",
      model: "per-unit",
    },
    distribution: ["Fintech compliance leads", "Microfinance and cooperative networks", "Core-banking vendors as partners"],
    split: {
      llm: "Reads and transcribes documents",
      decide: "Document type, legibility, obvious tampering signals",
      code: "Field comparison, expiry dates, tier rules",
    },
    tags: ["kyc", "compliance", "fintech"],
  },

  // Acquirers: the picks and shovels of AI roll-ups (see research/ai-rollups.md)
  {
    slug: "acquisition-automation-map",
    name: "Acquisition Automation Map",
    category: "service",
    status: "beta",
    oneLiner: "Before you sign the LOI: every task in the target firm mapped to what agents can take over, with the margin model.",
    pitch:
      "Due diligence before buying or acquiring a services business such as an accounting, bookkeeping, payroll, insurance, property management or IT managed services firm: from 20–50 anonymized work samples, a map of every task the target does, which tasks AI agents can take over after the acquisition, and the margin model, for searchers, holdcos and private equity buyers before they sign the letter of intent (LOI)",
    audience: ["acquirers"],
    unit: "One target firm mapped from 20–50 anonymized work samples, with the margin model",
    intake: [
      "20–50 anonymized completed jobs from the target, across its main services",
      "Monthly volume per service and headcount by role, from the seller or the CIM",
      "Two years of P&L",
      "Your deal terms: price, financing and the margin you need",
      "An NDA with the seller, and the seller's consent to share samples",
    ],
    engine:
      "Agents extract every task from the samples: trigger, inputs, steps, output, minutes and monthly volume. The brain scores each task's checkability and risk and classes it: automate now, automate with human review, assist only, or keep human. Code builds the margin model from the target's own volumes and costs.",
    rulebook: [
      "Every task cites the work samples it came from; nothing is inferred from the broker's summary alone.",
      "Minutes and volumes come from the target's own records; where there are none, the map says 'estimate' and shows the range.",
      "Anything that files, signs, pays or goes out in a client's name is at most 'automate with human review', at any confidence.",
      "The margin model runs on the target's own numbers, holds revenue flat and shows every formula; peers' self-reported results never go in.",
      "Every map names the tasks and client relationships that depend on one person, the owner above all.",
      "Samples arrive anonymized or under NDA; client names and personal data are stripped before a model sees them.",
      "We never bid for a firm we mapped for a client, and nothing learned in a client's diligence feeds our own deals.",
    ],
    review: "The founder reviews every map line by line; every 'automate now' call is checked by hand against its samples.",
    delivery:
      "A report page and a spreadsheet: one row per task with its class, the margin model with every formula, the risks to price in, and a 30-minute walkthrough.",
    turnaround: "5 working days after the samples arrive",
    price: {
      label: "$2,500 per target",
      humanAlternative: "Operational due diligence from a consulting firm at $10,000–$30,000",
      model: "per-unit",
    },
    checkout: { amountUsd: 1250, label: "50% deposit on one target ($2,500)" },
    distribution: [
      "Search-fund and ETA communities, with an anonymized sample map as the screenshot",
      "Business brokers, deal lawyers and quality-of-earnings accountants who already serve buyers",
      "Holdco and roll-up operators on X and LinkedIn",
    ],
    split: {
      llm: "Extracts tasks from the work samples and writes the map",
      decide: "Scores checkability and risk; classes each task: automate now, with review, assist or keep human",
      code: "Minutes, volumes, cost per task and the margin model",
    },
    tags: ["acquisitions", "due-diligence", "roll-ups", "automation-map", "margins"],
  },
  {
    slug: "agent-integration-100",
    name: "100-Day Agent Integration",
    category: "service",
    status: "beta",
    oneLiner: "After the close: agents take over the back office in 100 days, and the clients and key staff stay.",
    pitch:
      "Post-acquisition integration for buyers who just acquired or closed on a services business such as an accounting, bookkeeping, payroll, insurance, property management or IT managed services firm: a 100-day plan to integrate AI agents into its back office without losing clients or key staff, with shadow mode first, a rulebook written with senior staff, a preparer agent and a separate reviewer, a weekly corrections log, and a Monday dashboard of margin and retention",
    audience: ["acquirers"],
    unit: "One acquired firm integrated over 100 days, then monthly agent operations",
    intake: [
      "The Acquisition Automation Map, or 20–50 anonymized work samples to build one",
      "Read-only access to the firm's practice software, email and document store",
      "Two hours with each senior staff member for the rulebook interviews",
      "The former owner's time for the announcement and the handoff",
      "Who approves what: filings, payments and anything sent in a client's name",
    ],
    engine:
      "Days 1–30 change nothing clients see: agents run in shadow mode while senior staff write the rulebook. Days 31–60 move intake, document collection and the highest-volume, lowest-risk task to a preparer agent, with every draft reviewed. Days 61–100 add the next two tasks and a client-comms agent for routine status updates only. A separate reviewer agent can block but never ship; the preparer ships nothing on its own.",
    rulebook: [
      "Days 1–30 change nothing clients see: shadow mode only, and the deal is announced together with the former owner.",
      "No rule is active until the senior staff member it came from approves it; every approved rule becomes a test case.",
      "The preparer and the reviewer are separate agents: the reviewer can block but never ship, and the preparer ships nothing on its own.",
      "Filings, payments and anything sent in a client's name wait for a person's approval at any confidence.",
      "Every week, agent drafts are compared with the approved versions; each change is classed as a factual error, client preference, missing information or style, and a repeated correction becomes a proposed rule.",
      "Client and key-person retention are reported next to margin every Monday; if margin rises while client retention falls, automation stops expanding.",
      "The client-comms agent sends routine status updates only; advice, fees and bad news go to a person.",
    ],
    review:
      "The firm's own staff review every agent draft; Shonin reads the decision and corrections logs weekly and runs a monthly corrections review with senior staff.",
    delivery:
      "Agents live in the firm's own tools, the rulebook and corrections log in its own folder, and the Monday dashboard (margin, client retention, key-person retention, human minutes per job, corrections per job); a runbook at day 100, then monthly agent operations.",
    turnaround: "100 days, then monthly",
    price: {
      label: "From $12,000 per firm + $1,500/month agent ops",
      humanAlternative: "An operating partner or integration team at $150,000+ a year",
      model: "retainer",
    },
    checkout: { amountUsd: 6000, label: "50% deposit on one firm ($12,000)" },
    distribution: [
      "Acquisition Automation Map clients whose deals close",
      "Buyers who just closed, through their brokers, deal lawyers and lenders",
      "Case studies with the Monday numbers, published with the owner's consent",
    ],
    split: {
      llm: "Drafts the firm's work and routine client updates; turns staff interviews into draft rules",
      decide: "Routes each job, reviews each draft (block or pass), proposes rules from repeated corrections",
      code: "Deadlines, volumes, minutes per job, permissions and the Monday dashboard",
    },
    tags: ["acquisitions", "integration", "roll-ups", "rulebook", "back-office"],
  },

  // ─── Agent APIs: agents pay per call with x402 ───────────────────────────────
  {
    slug: "decide-api",
    name: "Decide API",
    category: "agent-api",
    status: "soon",
    oneLiner: "Typed decisions for agents: Choice, Score and Noul with confidence, in one call, paid per call.",
    pitch:
      "An HTTP API that AI agents and developers call to make typed decisions (pick one option, score on a scale, yes or no) with confidence, provider fallbacks and decision logs, paid per call with x402",
    audience: ["agents", "builders", "startup"],
    unit: "One decision call: up to 16 questions over up to 8k tokens of state",
    intake: ["An x402-capable client paying USDC, or an API key on an invoiced plan"],
    engine:
      "A System One model first, an LLM fallback second, schema validation always. Every answer says which provider answered, the model version, whether it was calibrated, and its confidence.",
    rulebook: [
      "Answers never leave the schema you asked for.",
      "Every response says whether the provider's probabilities were calibrated.",
      "State is treated as data, never as instructions.",
      "Flat distributions come back flagged: your options weren't distinguishable.",
      "Launches only after TypeSafe confirms in writing that its terms allow it. Until then: the recipe APIs, or TypeSafe directly.",
    ],
    review: "Automated: schema errors and flat distributions are flagged in the response.",
    delivery: "JSON over HTTPS.",
    turnaround: "~100–800 ms",
    price: {
      label: "$0.01 per decision",
      humanAlternative: "The same routing call on a frontier model costs more and returns a string you still have to parse",
      model: "per-call",
    },
    distribution: ["x402 Bazaar listing", "llms.txt and agent card on our domain", "MCP server"],
    split: { llm: "Fallback only", decide: "Everything you ask", code: "Validation, fallbacks, logging, billing" },
    tags: ["api", "x402", "jev", "agents"],
    api: {
      method: "POST",
      path: "/api/v1/decide",
      priceUsd: 0.01,
      description: "Answer up to 16 typed questions (choice, score, noul) about a state in one call.",
      inputExample: {
        state: { message: "I was charged twice for order A-104. Please refund the duplicate." },
        questions: {
          team: {
            type: "choice",
            instructions: "Which team should handle this",
            criteria: { billing: "Payments, refunds, duplicate charges", technical: "Bugs", other: "Anything else" },
          },
          refund: { type: "noul", instructions: "The customer is explicitly asking for a refund" },
        },
      },
    },
  },
  {
    slug: "triage-api",
    name: "Triage API",
    category: "agent-api",
    status: "beta",
    oneLiner: "Send a support message, get intent, complexity, frustration, refund intent and a route.",
    pitch:
      "An API that classifies a customer support message and returns intent, complexity, frustration, refund intent and the recommended route (code, specialist LLM or human)",
    audience: ["agents", "startup"],
    unit: "One message triaged",
    intake: ["subject and message text"],
    engine: "The support-triage recipe: one System One call and a deterministic cascade.",
    rulebook: ["Refunds route to a person.", "Very angry customers route to a person.", "Order status routes to code."],
    review: "Automated.",
    delivery: "JSON over HTTPS.",
    turnaround: "~100–800 ms",
    price: { label: "$0.01 per message", humanAlternative: "A person triaging by hand", model: "per-call" },
    distribution: ["x402 Bazaar", "llms.txt", "Support Triage Desk customers"],
    split: { llm: "None", decide: "Intent, complexity, frustration, refund", code: "The routing cascade" },
    tags: ["api", "x402", "support"],
    api: {
      method: "POST",
      path: "/api/v1/triage",
      priceUsd: 0.01,
      description: "Triage one support message and get a route.",
      inputExample: { subject: "Duplicate charge", message: "I was charged twice for order A-104. Please refund the duplicate." },
    },
  },
  {
    slug: "lead-score-api",
    name: "Lead Score API",
    category: "agent-api",
    status: "beta",
    oneLiner: "Score an inbound lead against your own offers: fit, urgency, budget, decision maker, spam.",
    pitch:
      "An API that scores an inbound sales lead against a list of offers you provide and returns the best-fit offer, urgency, budget signal, decision-maker probability, spam probability and a next step",
    audience: ["agents", "startup", "smb"],
    unit: "One lead scored",
    intake: ["message text and your offers (slug, name, pitch)"],
    engine: "The lead-routing recipe: one System One call and deterministic prioritization.",
    rulebook: ["Spam is discarded.", "Unclear fits go to a person.", "Priority is computed in code, not by the model."],
    review: "Automated.",
    delivery: "JSON over HTTPS.",
    turnaround: "~100–800 ms",
    price: { label: "$0.01 per lead", humanAlternative: "An SDR qualifying by hand", model: "per-call" },
    distribution: ["x402 Bazaar", "llms.txt"],
    split: { llm: "None", decide: "Offer fit, urgency, budget, decision maker, spam", code: "Priority and next step" },
    tags: ["api", "x402", "sales"],
    api: {
      method: "POST",
      path: "/api/v1/lead-score",
      priceUsd: 0.01,
      description: "Score an inbound lead against your offers and get a priority and next step.",
      inputExample: {
        message: "We need a WhatsApp assistant for our 3 restaurants before December. Budget approved.",
        offers: [
          { slug: "concierge", name: "WhatsApp Concierge", pitch: "An AI assistant that answers customers on WhatsApp" },
          { slug: "website", name: "Website", pitch: "A new website" },
        ],
      },
    },
  },
  {
    slug: "grant-fit-api",
    name: "Grant Fit API",
    category: "agent-api",
    status: "beta",
    oneLiner: "Score a grant application against a rubric and get the three sections to fix first.",
    pitch:
      "An API that scores a grant application or proposal against a funder's rubric and returns a 0–100 score, per-criterion scores, eligibility, unsupported claims and the sections to fix first",
    audience: ["agents", "builders", "ecosystems"],
    unit: "One application scored",
    intake: ["program name, requirements, application text, optional rubric"],
    engine: "The grant-fit recipe: one Score per rubric criterion plus eligibility and readiness Nouls.",
    rulebook: ["Scores come with the weakest criteria named.", "Unsupported claims are flagged.", "Eligibility is a probability, not a verdict."],
    review: "Automated; the Grant Desk adds human review.",
    delivery: "JSON over HTTPS.",
    turnaround: "~1–3 s",
    price: { label: "$0.05 per application", humanAlternative: "A reviewer's hour", model: "per-call" },
    distribution: ["x402 Bazaar", "Free web version as a Grant Desk lead magnet"],
    split: { llm: "None", decide: "Per-criterion scores, eligibility, readiness, unsupported claims", code: "Weighting and verdict" },
    tags: ["api", "x402", "grants"],
    api: {
      method: "POST",
      path: "/api/v1/grant-fit",
      priceUsd: 0.05,
      description: "Score an application against a rubric.",
      inputExample: {
        program: "Ecosystem builder grant",
        requirements: "Open source; live on mainnet; clear milestones",
        application: "We are building...",
      },
    },
  },
  {
    slug: "content-gate-api",
    name: "Content Gate API",
    category: "agent-api",
    status: "beta",
    oneLiner: "Should this draft ship? Hook, specificity, voice and unsourced-number checks in one call.",
    pitch:
      "An API that decides whether a draft post, thread or article is ready to publish, scoring the hook, specificity and voice, flagging unsourced numbers, and returning the fixes to make",
    audience: ["agents", "builders"],
    unit: "One draft judged",
    intake: ["draft text"],
    engine: "The content-gate recipe.",
    rulebook: ["Unsourced numbers block publishing.", "Generic AI voice goes back for revision."],
    review: "Automated.",
    delivery: "JSON over HTTPS.",
    turnaround: "~100–800 ms",
    price: { label: "$0.01 per draft", humanAlternative: "An editor's pass", model: "per-call" },
    distribution: ["x402 Bazaar", "Content agents and schedulers"],
    split: { llm: "None", decide: "Hook, specificity, voice, unsourced numbers, readiness", code: "Verdict and fix list" },
    tags: ["api", "x402", "content"],
    api: {
      method: "POST",
      path: "/api/v1/content-gate",
      priceUsd: 0.01,
      description: "Judge whether a draft is ready to publish and list the fixes.",
      inputExample: { draft: "Most agents rent a frontier model to return the word 'billing'..." },
    },
  },

  {
    slug: "market-prices-api",
    name: "Lagos Market Prices API",
    category: "agent-api",
    status: "soon",
    oneLiner: "Daily prices for staples in Lagos markets, sold per query to agents and apps, paid in stablecoins.",
    pitch:
      "A pay-per-query API of daily food and staple prices from Lagos markets for AI agents, fintechs, researchers and apps, paid per call with x402 in USDC or NGNm on Celo",
    audience: ["agents", "startup", "ecosystems"],
    unit: "One query",
    intake: ["An x402-capable client"],
    engine:
      "Field contributors send prices by WhatsApp photo or voice note; code extracts and dedupes; the brain scores each submission's plausibility; outliers go to a person.",
    rulebook: [
      "Every price has a market, a date and a contributor.",
      "Outliers beyond two standard deviations are held for review.",
      "Contributors are paid per verified submission.",
    ],
    review: "Daily outlier review.",
    delivery: "JSON over HTTPS.",
    turnaround: "Real time; data refreshed daily",
    price: { label: "$0.01 per query", humanAlternative: "Sending someone to the market", model: "per-call" },
    distribution: ["x402 Bazaar", "Agri-lending and fintech teams", "Researchers and journalists"],
    split: {
      llm: "Transcribes voice notes and photos",
      decide: "Plausibility of each submission",
      code: "Dedupe, averages, outlier statistics, billing",
    },
    tags: ["data", "x402", "lagos", "prices"],
    api: {
      method: "GET",
      path: "/api/v1/market-prices",
      priceUsd: 0.01,
      description: "Latest price of an item in a Lagos market.",
      inputExample: { market: "mile-12", item: "rice-50kg" },
    },
  },

  // ─── Infra ──────────────────────────────────────────────────────────────────
  {
    slug: "omni402",
    name: "Omni402 Gateway",
    category: "infra",
    status: "live",
    featured: true,
    oneLiner: "Make any HTTP API payable by AI agents: x402 gateway plus MCP server, gasless USDC on Celo.",
    pitch:
      "An x402 payment gateway and MCP server that turns any existing HTTP API into an endpoint AI agents can discover and pay for per call in USDC on Celo, with gasless settlement and an onchain agent identity",
    audience: ["builders", "startup", "agents"],
    unit: "One API made agent-payable",
    intake: ["Your API's base URL and routes", "Price per route", "Payout wallet"],
    engine: "x402 payment requirements in front of your routes, EIP-3009 gasless USDC settlement, an MCP server so agents can discover and call it.",
    rulebook: [
      "Price per route, never per seat.",
      "Settlement proofs are onchain and linkable.",
      "Agents discover the API from machine-readable metadata, not docs written for people.",
    ],
    review: "Settlement is verified onchain for every call.",
    delivery: "Gateway config, MCP server, discovery metadata.",
    turnaround: "1–3 days",
    price: {
      label: "Open source · setup service from $500",
      humanAlternative: "Building payments, metering and API keys in-house takes weeks",
      model: "per-unit",
    },
    distribution: ["Open-source repo", "Agent builder communities", "Hackathons"],
    split: { llm: "None", decide: "None", code: "Payment verification, settlement, routing" },
    tags: ["x402", "mcp", "celo", "usdc", "erc-8004"],
    links: [
      { label: "Repository", href: "https://github.com/eddiemessiah/omni402" },
      { label: "ERC-8004 agent #9765", href: "https://8004scan.io/agents/celo/9765" },
    ],
  },

  {
    slug: "agent-spend-firewall",
    name: "Agent Spend Firewall",
    category: "infra",
    status: "beta",
    featured: true,
    oneLiner: "A policy layer between an agent and its wallet: budgets, intent checks, human approval and a receipt for every payment.",
    pitch:
      "A spend firewall for AI agents that pay: before an agent pays an x402 endpoint or sends stablecoins, code checks budgets and allowlists, a System One model checks the payment matches what the user asked for, large or unusual payments go to a person, and every payment gets a receipt",
    audience: ["builders", "startup", "agents"],
    unit: "One agent wallet protected, per month",
    intake: ["The agent's wallet (Celo or Base)", "Budgets and allowlists", "Who approves what, and where (Telegram or Slack)"],
    engine:
      "Code enforces budgets and allowlists first; the brain answers 'does this payment match the user's intent?' and 'is this endpoint what it claims to be?'; a person approves anything above the limit; receipts are signed and stored.",
    rulebook: [
      "Budgets and allowlists are enforced in code before any model is asked.",
      "No payment above the per-transaction limit without a person's approval.",
      "Every payment gets a receipt: what, why, which decision, who approved.",
      "A model can block a payment. It can never raise a limit.",
    ],
    review: "Weekly review of blocked and approved payments.",
    delivery: "Middleware for your agent, an approval channel, and a receipts view.",
    turnaround: "3 days",
    price: {
      label: "$49/month per agent wallet + 0.5% of approved volume",
      humanAlternative: "A finance team reviewing every agent purchase by hand",
      model: "retainer",
    },
    distribution: ["Agent builders using x402 and Omni402", "Celo and Base agent communities", "Hackathons"],
    split: {
      llm: "Explains blocked payments to the user in plain language",
      decide: "Intent match, endpoint legitimacy, anomaly",
      code: "Budgets, allowlists, limits, signing, receipts",
    },
    tags: ["x402", "payments", "security", "celo", "jev"],
  },

  // ─── Community & talent ──────────────────────────────────────────────────────
  {
    slug: "ai-study-group",
    name: "AI Study Group",
    category: "community",
    status: "live",
    featured: true,
    oneLiner: "A global study group for becoming an AI engineer: free tracks, paid cohorts, city chapters, onchain certificates.",
    pitch:
      "Learn to build AI agents and become an AI engineer with a global study group: free self-paced tracks on agentic AI, ethical AI in Africa, inference engineering and onchain agents, plus live cohorts, study pods, city chapters, certificates on Celo, and a path to a job or paid work",
    audience: ["learners", "builders"],
    unit: "One learner in one track",
    intake: ["What you want to build or learn", "Your level and hours per week", "Timezone"],
    engine: "The academy (lessons, checks, server-graded quizzes, XP) plus the brain placing each applicant in a track, level and pod.",
    rulebook: [
      "Every phase ends with something shipped, not just watched.",
      "Pods of 5–8 at the same level and timezone meet weekly.",
      "Certificates are earned by passing server-graded quizzes and a reviewed capstone.",
    ],
    review: "Mentors review capstones; the brain flags learners who stall for a nudge from a person.",
    delivery: "Tracks, weekly pods, cohort sessions, certificates on Celo.",
    turnaround: "Rolling; cohorts start monthly",
    price: {
      label: "Free · Pro cohorts $49 · Team seats",
      ngn: "Pro ₦25,000",
      humanAlternative: "Bootcamps charge $500–$5,000",
      model: "cohort",
    },
    checkout: { amountUsd: 49, label: "One Pro cohort seat" },
    distribution: ["City chapters led by alumni", "Workshops and hackathons", "Sponsored tracks by ecosystems and employers"],
    split: {
      llm: "Explains, gives feedback, generates practice",
      decide: "Places applicants, grades short answers, flags stalls",
      code: "Progress, XP, streaks, certificates",
    },
    tags: ["education", "community", "certificates", "celo"],
  },
  {
    slug: "shonin-bench",
    name: "Shonin Bench",
    category: "community",
    status: "soon",
    oneLiner: "Vetted AI builders from the Study Group, available for contract work and forward-deployed roles.",
    pitch:
      "Hire vetted AI engineers and agent builders who earned Builder certificates in the AI Study Group, for contract work, forward-deployed engineering and full-time roles",
    audience: ["startup", "enterprise"],
    unit: "One placement or contract",
    intake: ["Role, stack and timezone", "Budget", "Start date"],
    engine: "Certificates, shipped capstones and decision-logged assessments as the vetting signal.",
    rulebook: [
      "Only Builder-certified members are listed.",
      "Every profile links to shipped work.",
      "Clients rate every engagement; low ratings end listings.",
    ],
    review: "A person interviews every member before listing.",
    delivery: "Shortlist in 72 hours.",
    turnaround: "72 hours to shortlist",
    price: { label: "15% of first-year salary or contract value", humanAlternative: "Recruiters charge 20–30%", model: "per-unit" },
    distribution: ["Clients of the services arm", "Ecosystem partners hiring builders"],
    split: { llm: "Writes profiles from shipped work", decide: "Matches roles to candidates", code: "Scheduling, contracts, payouts" },
    tags: ["talent", "hiring", "fde"],
  },

  // ─── Research & media ────────────────────────────────────────────────────────
  {
    slug: "griot",
    name: "Griot",
    category: "research",
    status: "live",
    oneLiner: "Field notes on AI in Africa: research, teardowns and builder guides, published weekly.",
    pitch:
      "A research desk and newsletter on AI in Africa: infrastructure, models, policy and the builders shipping real products, with teardowns and tutorials for engineers",
    audience: ["builders", "ecosystems", "learners"],
    unit: "One issue per week; sponsor slots",
    intake: ["Subscribe, or pitch a story"],
    engine: "Research agents gather and extract; the brain scores sources and gates drafts; the founder edits.",
    rulebook: [
      "Every claim has a source link and every number has a date.",
      "Unverified items go in their own section.",
      "Sponsors are labelled and never edit the research.",
    ],
    review: "Every issue is edited by a person.",
    delivery: "Newsletter, site archive, X threads.",
    turnaround: "Weekly",
    price: { label: "Free · sponsor slots from $300", humanAlternative: "—", model: "sponsorship" },
    distribution: ["X threads", "Study Group members", "Event talks"],
    split: { llm: "Drafts summaries", decide: "Source relevance and credibility; publish gate", code: "Scheduling, archive, analytics" },
    tags: ["research", "newsletter", "africa"],
  },
  {
    slug: "ecosystem-intel",
    name: "Ecosystem Intelligence Reports",
    category: "research",
    status: "beta",
    oneLiner: "Sourced reports and datasets on who is building what with AI in Africa, for ecosystems, funds and foundations.",
    pitch:
      "Research reports and datasets on African AI and Web3 builders, startups, programs and policy for blockchain ecosystems, VCs, foundations and development organizations",
    audience: ["ecosystems", "enterprise"],
    unit: "One report with its dataset",
    intake: ["The research question", "Geography and sectors", "Who will read it", "Public or private"],
    engine: "Research agents gather and extract; the brain scores source credibility and relevance; an editor writes the narrative.",
    rulebook: [
      "Every claim has a source link; every number has a date.",
      "Primary sources beat press releases; press releases beat social posts.",
      "What we couldn't verify gets its own section.",
      "No ranking without a published method.",
    ],
    review: "An editor verifies every chart and a 20% sample of claims.",
    delivery: "A web report, the dataset as CSV, and a briefing call.",
    turnaround: "2–3 weeks",
    price: { label: "From $2,500 per report", humanAlternative: "Research firms charge $10,000–$50,000", model: "per-unit" },
    distribution: ["Free summaries, paid datasets and briefings", "Ecosystem and fund teams at events", "Griot readers"],
    split: {
      llm: "Extracts facts and writes the narrative",
      decide: "Scores relevance and credibility of every source; flags contradictions",
      code: "Dedupes, dates, counts and charts",
    },
    tags: ["research", "data", "africa", "reports"],
  },
  {
    slug: "afroeval",
    name: "AfroEval",
    category: "research",
    status: "soon",
    oneLiner: "Test your agent in Pidgin, Yoruba, Hausa, Igbo, Swahili and Twi before your customers do.",
    pitch:
      "A cost-aware evaluation harness for AI agents in African languages and contexts: task suites in Nigerian Pidgin, Yoruba, Hausa, Igbo, Swahili and Twi, plus local compliance rules, measuring accuracy, cost and reliability",
    audience: ["startup", "enterprise", "ecosystems"],
    unit: "One agent evaluated across a language suite",
    intake: ["Agent endpoint", "Target languages", "Task types"],
    engine: "Task suites written with native speakers; repeated runs for consistency; cost tracked per task, so results read as accuracy per dollar.",
    rulebook: [
      "Native speakers write and verify every task.",
      "Report accuracy per dollar, not just accuracy.",
      "Publish the method; keep test sets private so nobody trains on them.",
    ],
    review: "Native-speaker reviewers score a sample of every run.",
    delivery: "A scorecard per language and task, with failing examples.",
    turnaround: "1–2 weeks",
    price: { label: "From $1,500 per run", humanAlternative: "Hiring native-speaker QA per language", model: "per-unit" },
    distribution: ["Model labs and startups expanding into Africa", "Language coalition partners", "Published results via Griot"],
    split: {
      llm: "Proposes candidate tasks for native speakers to verify",
      decide: "Grades answers against rubrics",
      code: "Runs suites, repeats, computes cost and accuracy",
    },
    tags: ["evals", "african-languages", "research"],
  },
];
